## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [11]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [12]:
# 讀取boston資料集
boston = datasets.load_boston()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)

# 建立一個 LASSO回歸模型 alpha = 1.0
lasso = linear_model.Lasso(alpha=1.0)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

# 印出各特徵對應的係數
print(lasso.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

[-0.06494981  0.04581458 -0.          0.         -0.          1.18140024
  0.01109101 -0.73695809  0.23350042 -0.01551065 -0.69270805  0.00763157
 -0.6927848 ]
Mean squared error: 28.95


In [13]:
# 建立一個 LASSO回歸模型 alpha = 0.1
lasso = linear_model.Lasso(alpha=0.1)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

# 印出各特徵對應的係數
print(lasso.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

[-0.10618872  0.04886351 -0.04536655  1.14953069 -0.          3.82353877
 -0.02089779 -1.23590613  0.26008876 -0.01517094 -0.74673362  0.00963864
 -0.49877104]
Mean squared error: 26.45


In [14]:
# 建立一個 Ridge回歸模型 alpha = 1.0
ridge = linear_model.Ridge(alpha=1.0)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = ridge.predict(x_test)

# 印出各特徵對應的係數
print(ridge.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

[-1.12499445e-01  4.79562332e-02 -2.40438147e-02  2.96199458e+00
 -9.33966118e+00  3.93079015e+00 -1.73821202e-02 -1.43347691e+00
  2.75239392e-01 -1.38920708e-02 -8.31116943e-01  9.15637729e-03
 -4.66460539e-01]
Mean squared error: 25.74


In [15]:
# 建立一個 Ridge回歸模型 alpha = 0.1
ridge = linear_model.Ridge(alpha=0.1)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = ridge.predict(x_test)

# 印出各特徵對應的係數
print(ridge.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

[-1.15381303e-01  4.72528249e-02  2.87371589e-03  3.19642306e+00
 -1.54713824e+01  3.89388927e+00 -1.19943742e-02 -1.52347878e+00
  2.90133016e-01 -1.34816989e-02 -8.93679905e-01  8.86599187e-03
 -4.58983115e-01]
Mean squared error: 25.46


In [16]:
# 讀取linnerud資料集
linnerud = datasets.load_linnerud()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(linnerud.data, linnerud.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型 alpha = 1.0
lasso = linear_model.Lasso(alpha=1.0)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

# 印出各特徵對應的係數
print(lasso.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

[[-1.21702413 -0.18301572  0.07085454]
 [-0.16500267 -0.04240416  0.02848377]
 [ 0.10302969  0.05543243 -0.03005608]]
Mean squared error: 382.88


In [17]:
# 建立一個線性回歸模型 alpha = 0.1
lasso = linear_model.Lasso(alpha=0.1)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

# 印出各特徵對應的係數
print(lasso.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

[[-1.28050477 -0.18035845  0.0723055 ]
 [-0.22848573 -0.03974737  0.02993522]
 [ 0.16650656  0.05277535 -0.031507  ]]
Mean squared error: 385.82


In [18]:
# 建立一個 Ridge回歸模型 alpha = 1.0
ridge = linear_model.Ridge(alpha=1.0)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = ridge.predict(x_test)

# 印出各特徵對應的係數
print(ridge.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

[[-1.28169016 -0.18036401  0.072403  ]
 [-0.23446277 -0.03950683  0.03008403]
 [ 0.17278069  0.05251903 -0.03165848]]
Mean squared error: 385.93


In [19]:
# 建立一個 Ridge回歸模型 alpha = 0.1
ridge = linear_model.Ridge(alpha=0.1)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = ridge.predict(x_test)

# 印出各特徵對應的係數
print(ridge.coef_)

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

[[-1.28697432 -0.18008663  0.07245527]
 [-0.23542857 -0.03945666  0.03009432]
 [ 0.17348754  0.05248312 -0.03166684]]
Mean squared error: 386.13
